" Common misspellings
iabbr challegne challenge
iabbr challegnes challenges
iabbr shoudl should
iabbr shuold should
iabbr shuold_not should_not
iabbr shuold_receive should_receive
iabbr sohuld should
iabbr teh the
