" No GUI elements. At all. okthxbai
set t_Co=256
set guioptions=aic

" Maximize to full width and height
if has("mac")
  set fuoptions=maxvert,maxhorz
  set guifont=Ubuntu\ Mono\ for\ Powerline\ for\ Powerline:h14
else
  "set guifont=Ubuntu\ Mono\ derivative\ Powerline\ 12
  set guifont=Terminus\ Bold\ 9
endi

"nnoremap <F2> :set guifont=Terminus\ Bold\ 9<CR>
"nnoremap <F3> :set guifont=Terminus\ Bold\ 11<CR>
"nnoremap <F4> :set guifont=Ubuntu\ Mono\ derivative\ Powerline\ 12<CR>
nnoremap <F6> :call CycleFont()<CR>

func! CycleFont()
  let fonts = [
        \"Terminus Bold 9",
        \"Terminus Bold 11",
        \"Ubuntu Mono derivative Powerline 12",
        \"Hack 9",
        \"Fira Code 9",
        \]

  let current_font = &guifont

  for font in fonts
    if current_font == font
      let idx = index(fonts, font) + 1

      if idx > (len(fonts) - 1)
        let idx = 0
      end

      execute ':set guifont=' . substitute(fonts[idx], ' ', '\\ ', 'g')
      echo system('i3-msg fullscreen; i3-msg fullscreen')
      redraw " Force redraw so that echoed text is left in the status line
      echo 'Changing to [' . fonts[idx] . '] from [' . font . ']'
    endi
  endfor
endf

set antialias
